### PR TITLE
Fix consecutive calls

### LINKED ISSUE #24: Shared workerfarm reference prevents sequential directory conversions
Hello! First of all, thank you for this most excellent tool. It's been wonderfully helpful to our workflow.

We are using this via grunticon (via gulpicon), and have a scenario with multiple icon directories (for themes). In our gulp task, we process each folder with icons one after the other, within the same process.

The problem we've encountered is that after the first folder processes, subsequent calls fail to convert any -color-*.svgs, and then the process hangs, without any errors. I've tracked it down to this module, and having had a look around, discovered two things:

1. In `colorfy.js`: Since `workerFarm.end` is called after the first round of icons is processed (ie, the first directory), subsequent calls receive a 'false' value for `result` here: 
	```
		var endWorkers = function(err) {
			// kill child processes
			var result = workerFarm.end(workers, function() {
				callback(err, 'done');
			});
			// worker end returns early if the workers are already killed
			if( result === false ){
				callback(err, 'done');
			}
		};
	```
	and so the 'done' parameter is passed the first time it runs, despite not having processed all files, which causes the promise to resolve prematurely.

	Adding a check to the complete handler in `directory-colorfy.js`:
	```
	complete: function() {
   	 if (converted.length === colorfied.length) {
        	resolve(filesWritten);
    	}
	}
	```
	prevented the promise being resolved prematurely, so subsequent files were successfully processed, but it didn't solve the fundamental issue, which meant that the process was still hanging, which brings me to two:

2. Since the `workers` instance in `colorfy.js` is shared between all `Colorfy` instances, once it's been ended, any subsequent calls to start and stop the workers don't end properly. (I imagine this only causes an issue in our scenario, when we're calling directory covert multiple times in the same process.) 
By moving the instantiation to the `_convert` method, it solved all the issues we were having:
	```
	var _convert = function( colors, originalFilepath, ofnNoExt, originalContents, callback ){
		var color = "",
			newFilePath = "",
			newFilename = "";
		var files = [];
		var workers = workerFarm(require.resolve( path.join( __dirname, "convert" ) ) );
		[...]
	}
	```

Below are two stacktraces that demonstrate the difference, first is with the shared instance (albeit with the `complete` check described in 1.), and the second is with unique instances. As you can see, there seems to be a negligible effect on performance.

I'm happy to do a PR if that would be helpful. 

The first - you can see that `farm.end` calls are made in the first directory pass, but not in subsequent ones:

```
[14:39:39] Starting 'icons:grumpicon'...
[14:39:39] Icons for core have changed
[14:39:39] Icons for melody have changed
[14:39:39] Icons for nautilus have changed
[14:39:39] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/core/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-up-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-response-edit.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-response-error.colors-error.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-task-incoming.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-task-outgoing.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-tasks.colors-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-tick-open.colors-success.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-warning.colors-error.svg
startChild: 0
startChild: 1
startChild: 2
startChild: 3
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 3
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 3
Farm end called; is complete?  false
: checking length 2 3
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 3
Farm end called; is complete?  false
: checking length 2 3
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 1 2
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
stopChild: 0
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 3
stopChild: 3
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 1 1
> calling endWorkers 1 1
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 2 2
> calling endWorkers 2 2
Farm end called; is complete?  false
worker has ended early? false
Farm end called; is complete?  false
: checking length 3 3
> calling endWorkers 3 3
Farm end called; is complete?  false
worker has ended early? false
stopChild: 1
Farm end called; is complete?  false
: checking length 3 3
> calling endWorkers 3 3
Farm end called; is complete?  false
worker has ended early? false
stopChild: 2
Farm end called; is complete?  true
: checking length 3 3
> calling endWorkers 3 3
Farm end called; is complete?  true
worker has ended early? false
check complete: 23 23
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:40:14] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-up-open.colors-blue-white.svg
startChild: 4
startChild: 5
startChild: 6
startChild: 7
: checking length 1 3
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 1 16
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 2 16
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 3 16
: checking length 1 2
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 4 16
: checking length 2 3
: checking length 3 3
> calling endWorkers 3 3
worker has ended early? true
check complete: 5 16
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 6 16
: checking length 1 2
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 7 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 8 16
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 9 16
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 10 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 11 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 12 16
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 13 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 14 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 15 16
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 16 16
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:40:42] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-up-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-response-edit.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-response-error.colors-error.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-task-incoming.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-task-outgoing.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-tasks.colors-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-tick-open.colors-success.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-warning.colors-error.svg
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 1 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 2 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 3 23
: checking length 1 2
: checking length 1 3
: checking length 2 3
: checking length 1 2
: checking length 1 2
: checking length 1 3
: checking length 3 3
> calling endWorkers 3 3
worker has ended early? true
check complete: 4 23
: checking length 1 2
: checking length 1 3
: checking length 1 2
: checking length 2 3
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 5 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 6 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 7 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 8 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 9 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 10 23
: checking length 1 2
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 11 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 12 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 13 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 14 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 15 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 16 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 17 23
: checking length 2 3
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 18 23
: checking length 2 2
> calling endWorkers 2 2
worker has ended early? true
check complete: 19 23
: checking length 3 3
> calling endWorkers 3 3
worker has ended early? true
check complete: 20 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 21 23
: checking length 1 1
> calling endWorkers 1 1
worker has ended early? true
check complete: 22 23
: checking length 3 3
> calling endWorkers 3 3
worker has ended early? true
check complete: 23 23
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:41:17] Finished 'icons:grumpicon' after 1.63 min

```

and the second; you can see the calls are made successfully with each pass:

```
[14:45:13] Starting 'icons:grumpicon'...
[14:45:13] Icons for core have changed
[14:45:13] Icons for melody have changed
[14:45:13] Icons for nautilus have changed
[14:45:13] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/core/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-page-up-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-response-edit.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-response-error.colors-error.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-task-incoming.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-task-outgoing.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-tasks.colors-white.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-tick-open.colors-success.svg
creating new Colorfy .icons/optimised_svgs/core/ff_icon-warning.colors-error.svg
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 0
startChild: 0
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 1 23
: checking length 1 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 2 23
: checking length 1 2
: checking length 2 3
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 3 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 4 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 5 23
: checking length 1 2
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 6 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 7 23
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 8 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 9 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 10 23
: checking length 1 2
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 11 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 12 23
: checking length 1 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 13 23
: checking length 2 3
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 14 23
: checking length 1 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 15 23
: checking length 2 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 16 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 17 23
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 18 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 19 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 20 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 21 23
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 22 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 23 23
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:45:48] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/melody/ff_icon-page-up-open.colors-blue-white.svg
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 1 16
: checking length 1 2
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 2 16
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 3 16
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 4 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 5 16
: checking length 1 3
: checking length 1 2
: checking length 1 2
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 6 16
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 7 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 8 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 9 16
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 10 16
: checking length 2 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 11 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 12 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 13 16
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 14 16
: checking length 1 2
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 15 16
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 16 16
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:46:18] Look, it's a gulpicon!
Creating new DirectoryColorfy
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-add-open.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-calendar.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-cancel-open.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-cancel.colors-grey-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-download-to.colors-greyblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-duplicate.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-edit.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-file-forward.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-folder.colors-white-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-help.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-back.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-down-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-down.colors-blue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-forward-open.colors-lightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-forward.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-page-up-open.colors-blue-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-response-edit.colors-blue-darkgrey.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-response-error.colors-error.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-task-incoming.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-task-outgoing.colors-grey-extradarkgrey-brightblue.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-tasks.colors-white.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-tick-open.colors-success.svg
creating new Colorfy .icons/optimised_svgs/nautilus/ff_icon-warning.colors-error.svg
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 1
startChild: 0
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 1
startChild: 2
startChild: 0
startChild: 0
startChild: 0
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 1 23
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 2 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 3 23
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 4 23
: checking length 1 2
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 5 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 6 23
: checking length 1 3
: checking length 1 2
: checking length 1 3
: checking length 2 3
: checking length 1 3
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 7 23
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 8 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 9 23
: checking length 2 3
: checking length 1 2
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 10 23
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 11 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 12 23
: checking length 1 2
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 13 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 14 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 15 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 16 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 17 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 18 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 19 23
: checking length 2 2
> calling endWorkers 2 2
stopChild: 0
stopChild: 1
Farm end called; is complete?  true
worker has ended early? false
check complete: 20 23
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 21 23
: checking length 2 3
: checking length 3 3
> calling endWorkers 3 3
stopChild: 0
stopChild: 1
stopChild: 2
Farm end called; is complete?  true
worker has ended early? false
check complete: 22 23
: checking length 1 1
> calling endWorkers 1 1
stopChild: 0
Farm end called; is complete?  true
worker has ended early? false
check complete: 23 23
svg-to-png now spawning phantomjs...
(using path: [path]/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[14:46:53] Finished 'icons:grumpicon' after 1.67 min

```

### PR DESCRIPTION
**Pull request by dkhuntrods**
This PR:
- implements the new workerFarm `revive` functionality in order to allow consecutive processing.
- adds tests for consecutive processing 
- updates the `large` test

Resolves #24

### CODE REVIEW

File: lib/directory-colorfy.js [hunk 1]
```diff
@@ -37,49 +37,51 @@
...
-	};
+            if (colorfied.length === 0) {
+                resolve(filesWritten);
+            } else {
+                colorfied.forEach(function(colorfy) {
+                    dirConvert(colorfy, handlers);
+                });
+            }
+        }.bind(null, this, promises));
+    };
```
Comment (johnbender) [inline lib/directory-colorfy.js]: Just checking in, these just seem to be whitespace changes so I will ignore them unless otherwise necessary.

File: test/directory-colorfy-consecutive_test.js [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+                .catch(function(err){
+                    console.log(err);
+                    test.done();
+                });
+            });
+
+        }
+    };
+
+}(typeof exports === 'object' && exports || this));
```
Comment (johnbender) [inline test/directory-colorfy-consecutive_test.js]: Let's avoid adding mixed case filenames if we can. Let's just stick with the `-`.

File: test/files/directory-colorfy/consecutive/book.svg [hunk 3]
```diff
@@ -2,5 +2,6 @@
 <!-- Generated by IcoMoon.io -->
 <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
 <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="64" height="64" viewBox="0 0 64 64">
-<path d="M32 0c-17.673 0-32 14.327-32 32s14.327 32 32 32 32-14.327 32-32-14.327-32-32-32zM32 58c-14.359 0-26-11.641-26-26s11.641-26 26-26 26 11.641 26 26-11.641 26-26 26zM20 20h24v24h-24z" fill="#000000"></path>
+<path d="M56 8v52h-42c-3.314 0-6-2.686-6-6s2.686-6 6-6h38v-48h-40c-4.4 0-8 3.6-8 8v48c0 4.4 3.6 8 8 8h48v-56h-4z" fill="#000000"></path>
+<path d="M14.004 52v0c-0.001 0-0.002 0-0.004 0-1.104 0-2 0.895-2 2s0.896 2 2 2c0.001 0 0.002-0 0.004-0v0h37.993v-4h-37.993z" fill="#000000"></path>
 </svg>
```
Comment (johnbender) [inline test/files/directory-colorfy/consecutive/book.svg]: Why the SVG mods?

File: lib/directory-colorfy.js (hunk 1 above)
Comment (dkhuntrods) [inline lib/directory-colorfy.js]: Yes, they are.

File: test/directory-colorfy-consecutive_test.js (hunk 2 above)
Comment (dkhuntrods) [inline test/directory-colorfy-consecutive_test.js]: No disagreement with the principle, however in this case that's the format that the existing test use, and its the regex for the test files:

```
nodeunit: {
			main: ['test/*_test.js'],
			large: ['test/large/directory-colorfy-large_test.js']
    }
```

File: test/files/directory-colorfy/consecutive/book.svg (hunk 3 above)
Comment (dkhuntrods) [inline test/files/directory-colorfy/consecutive/book.svg]: I copied some files from the `large` directory and just renamed them; this should be an add really so not sure why git tracked it as a mod. When I view the file it is definitely the book and not the `stop` file.

**Comment by johnbender** [comment]
@jefflembeck 

This looks great and all the tests pass. I also wanted to run the `grunticon-lib` tests with this update and they pass but they don't exercise the modified `_convert` function. I'm going to hack around with this for a bit but otherwise we should be able to merge soon.

Thanks for all the hard work @dkhuntrods!

**Comment by johnbender** [comment]
@dkhuntrods @jefflembeck 

Ok I don't have time right now to update the tests with the extra color annotated svg files but the output is correct and otherwise the tests pass just fine. 

screenshot 2016-08-02 12 45 33

Mergin'!

**Comment by dkhuntrods** [comment]
@johnbender Thanks for reviewing and merging so quickly. Just re-installed gulpicon and now all our theme icons build perfectly. Happy days!
